name: Build and Test
on: [push,pull_request]
jobs:
  Ubuntu-Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@eff1dce037c4c0143cc4180a810511024c2560c0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'
          java-package: jdk
          architecture: x64
          cache: gradle
      - name: Install prerequisites
        run: |
          wget https://imagemagick.org/archive/binaries/magick
          chmod +x magick
          sudo mv magick /usr/bin/
          sudo apt-get update
          sudo apt-get install xvfb tmux ffmpeg icewm bash
          bash run-xvfb-screens.sh
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0842a550d10f5211be8c8295f6888889e1fca291
        with:
          arguments: build -Pcheckers=all -PthreadCheck=true -Pheadless=false -Pxvfb=true -Pscreenrecord=true --info --stacktrace --no-daemon --scan
      - name: Archive video
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screen-recordings
          path: |
            **/*.mp4
            **/*.ffmpeg.log
      - name: Archive any heap dumps
        if: always()
        uses: actions/upload-artifact@v3
        with:
           name: heap-dumps
           path: |
              **/*.hprof
